var bombui=function(){function b(a,b,k,d,c){for(var e=[];a<b;a++)e.push({x:a*d,y:k,width:d,height:c});return e}function c(){var a=new Kinetic.Image({x:0,y:0,image:this,width:d.getWidth(),height:d.getHeight()});n.add(a);a=new Image;a.onload=h;a.src="images/bomb/sprite5.png"}function h(){m=new Kinetic.Sprite({x:0,y:405,image:this,animation:"normal",animations:q,frameRate:0});n.add(m);m.start();l=new Kinetic.Sprite({x:128,y:268,image:this,animation:"normal",animations:k,frameRate:0});n.add(l);l.start();
for(var b=0;4>b;b++){var d;d=b;var f=new Kinetic.Sprite({x:265+210*d,y:390,image:this,animation:3==b?"burning":"unlit",animations:a,frameRate:10});f.on("mouseover",_.partial(g,"mouseover"));f.on("mouseout",_.partial(g,"mouseout"));f.on("click touchstart",_.partial(e,d));d=f;p.push(d);n.add(d);d.start()}}function g(a,b){"burning"==this.getAnimation()&&(document.body.style.cursor="mouseover"==a?"pointer":"default")}function e(a,b){if("burning"==this.getAnimation()){document.body.style.cursor="default";
var k=this;k.setOffset(98,-50);k.stop();setTimeout(function(){l.setAnimation(a);0<a?p[a-1].setAnimation("burning"):(m.setAnimation("burnt"),soundmanager.playSound("soundScream"),m.start())},20);k.afterFrame(4,function(){k.stop();k.destroy()});k.setAnimation("explode");k.start();soundmanager.playSound("soundExplosion")}}var d,n,p=[],m,l,q={normal:[{x:35,y:1010,width:230,height:350}],burnt:[{x:305,y:1010,width:230,height:350}]},a={unlit:[{x:0,y:680,width:161,height:320}],burning:b(1,3,686,161,320),
explode:b(0,3,0,357,341).concat(b(0,3,342,357,341))},k={normal:[{x:0,y:1408,width:1070,height:87}],3:[{x:0,y:1496,width:1070,height:87}],2:[{x:0,y:1585,width:1070,height:82}],1:[{x:0,y:1670,width:1070,height:82}],0:[{x:0,y:1762,width:1070,height:87}]};return{init:function(a){d=new Kinetic.Stage({container:a,width:1280,height:780});soundmanager.preloadSounds(["soundExplosion","soundScream"]);n=new Kinetic.Layer({});d.add(n);a=new Image;a.onload=c;a.src="images/bomb/bombbackground.png"},setWidth:function(a){d.setScale(a/
1280)}}}(),birdAnimations=function(){function b(){for(var a=[],b=0;2>b;b++)for(var d=0;4>d;d++)a.push({x:200*d,y:210*b,width:200,height:210});return{flight:a}}function c(){q++;var a=Math.floor(12*Math.random())+4+n/p,k;k=5<l?Math.floor(Math.random()*(d.getHeight()-150)):Math.floor(Math.random()*((d.getHeight()-150)/(a/5)));var c=1.8/a*l,r=400*c,f=d.getWidth()/r,a=7,a=new Kinetic.Sprite({x:d.getWidth(),y:k,image:e,scale:c,animation:"flight",animations:b(),frameRate:a,index:a});g.add(a);a.start();a.on("mousedown",
function(a){console.log("click object",a,this)});(new Kinetic.Tween({node:a,duration:f,x:-r,onFinish:function(){this.node.destroy();this.destroy();q--;h()}})).play();h()}function h(){q<m+15&&setTimeout(c,Math.random()*p)}var g,e,d,n=5400,p=n,m=0,l=1,q=0;return{start:function(a,b){d=a;g=b;e=new Image;e.onload=c;e.src="images/birdsprite.png";soundmanager.preloadSounds(["soundBirdDeath"])},onClick:function(a){if((a=d.getIntersection(a))&&a.shape){a=a.shape;q--;var b=d.getHeight()-a.getY()+a.getHeight(),
b=Math.sqrt(b/200);m++;0==m%2&&(p*=0.66);0==m%10&&(l*=30<m?30:m,p*=3,setTimeout(function(){l=1;p=n},4E3));soundmanager.playSound("soundBirdDeath");(new Kinetic.Tween({node:a,duration:b,easing:Kinetic.Easings.EaseIn,y:d.getHeight()+a.getHeight(),onFinish:function(){this.node.destroy();this.destroy()}})).play();setTimeout(c,100)}}}}(),soundmanager=function(){var b={};return{preloadSounds:function(c){for(var h=0,g;g=c[h];h++){var e=document.getElementById(g);e&&e.play&&(e.volume=0,e.play(),b[g]=e,setTimeout(_.partial(function(b){b.pause();
b.volume=0.2},e),10))}},playSound:function(c){(c=b[c])&&c.play&&(c.paused||(c.currentTime=0),c.play())}}}();
(function(b){"function"===typeof define&&define.amd?define(["jquery"],b):b(jQuery)})(function(b){var c=[],h=b(document),g=navigator.userAgent.toLowerCase(),e=b(window),d=[],n=null,p=/msie/.test(g)&&!/opera/.test(g),m=/opera/.test(g),l,q;l=p&&/msie 6./.test(g)&&"object"!==typeof window.XMLHttpRequest;q=p&&/msie 7.0/.test(g);b.modal=function(a,k){return b.modal.impl.init(a,k)};b.modal.close=function(){b.modal.impl.close()};b.modal.focus=function(a){b.modal.impl.focus(a)};b.modal.setContainerDimensions=
function(){b.modal.impl.setContainerDimensions()};b.modal.setPosition=function(){b.modal.impl.setPosition()};b.modal.update=function(a,k){b.modal.impl.update(a,k)};b.fn.modal=function(a){return b.modal.impl.init(this,a)};b.modal.defaults={appendTo:"body",focus:!0,opacity:50,overlayId:"simplemodal-overlay",overlayCss:{},containerId:"simplemodal-container",containerCss:{},dataId:"simplemodal-data",dataCss:{},minHeight:null,minWidth:null,maxHeight:null,maxWidth:null,autoResize:!1,autoPosition:!0,zIndex:1E3,
close:!0,closeHTML:'<a class="modalCloseImg" title="Close"></a>',closeClass:"simplemodal-close",escClose:!0,overlayClose:!1,fixed:!0,position:null,persist:!1,modal:!0,onOpen:null,onShow:null,onClose:null};b.modal.impl={d:{},init:function(a,k){if(this.d.data)return!1;n=p&&!b.support.boxModel;this.o=b.extend({},b.modal.defaults,k);this.zIndex=this.o.zIndex;this.occb=!1;if("object"===typeof a){if(a=a instanceof b?a:b(a),this.d.placeholder=!1,0<a.parent().parent().size()&&(a.before(b("<span></span>").attr("id",
"simplemodal-placeholder").css({display:"none"})),this.d.placeholder=!0,this.display=a.css("display"),!this.o.persist))this.d.orig=a.clone(!0)}else if("string"===typeof a||"number"===typeof a)a=b("<div></div>").html(a);else return alert("SimpleModal Error: Unsupported data type: "+typeof a),this;this.create(a);this.open();b.isFunction(this.o.onShow)&&this.o.onShow.apply(this,[this.d]);return this},create:function(a){this.getDimensions();this.o.modal&&l&&(this.d.iframe=b('<iframe src="javascript:false;"></iframe>').css(b.extend(this.o.iframeCss,
{display:"none",opacity:0,position:"fixed",height:d[0],width:d[1],zIndex:this.o.zIndex,top:0,left:0})).appendTo(this.o.appendTo));this.d.overlay=b("<div></div>").attr("id",this.o.overlayId).addClass("simplemodal-overlay").css(b.extend(this.o.overlayCss,{display:"none",opacity:this.o.opacity/100,height:this.o.modal?c[0]:0,width:this.o.modal?c[1]:0,position:"fixed",left:0,top:0,zIndex:this.o.zIndex+1})).appendTo(this.o.appendTo);this.d.container=b("<div></div>").attr("id",this.o.containerId).addClass("simplemodal-container").css(b.extend({position:this.o.fixed?
"fixed":"absolute"},this.o.containerCss,{display:"none",zIndex:this.o.zIndex+2})).append(this.o.close&&this.o.closeHTML?b(this.o.closeHTML).addClass(this.o.closeClass):"").appendTo(this.o.appendTo);this.d.wrap=b("<div></div>").attr("tabIndex",-1).addClass("simplemodal-wrap").css({height:"100%",outline:0,width:"100%"}).appendTo(this.d.container);this.d.data=a.attr("id",a.attr("id")||this.o.dataId).addClass("simplemodal-data").css(b.extend(this.o.dataCss,{display:"none"})).appendTo("body");this.setContainerDimensions();
this.d.data.appendTo(this.d.wrap);(l||n)&&this.fixIE()},bindEvents:function(){var a=this;b("."+a.o.closeClass).bind("click.simplemodal",function(b){b.preventDefault();a.close()});a.o.modal&&a.o.close&&a.o.overlayClose&&a.d.overlay.bind("click.simplemodal",function(b){b.preventDefault();a.close()});h.bind("keydown.simplemodal",function(b){a.o.modal&&9===b.keyCode?a.watchTab(b):a.o.close&&a.o.escClose&&27===b.keyCode&&(b.preventDefault(),a.close())});e.bind("resize.simplemodal orientationchange.simplemodal",
function(){a.getDimensions();a.o.autoResize?a.setContainerDimensions():a.o.autoPosition&&a.setPosition();l||n?a.fixIE():a.o.modal&&(a.d.iframe&&a.d.iframe.css({height:d[0],width:d[1]}),a.d.overlay.css({height:c[0],width:c[1]}))})},unbindEvents:function(){b("."+this.o.closeClass).unbind("click.simplemodal");h.unbind("keydown.simplemodal");e.unbind(".simplemodal");this.d.overlay.unbind("click.simplemodal")},fixIE:function(){var a=this.o.position;b.each([this.d.iframe||null,this.o.modal?this.d.overlay:
null,"fixed"===this.d.container.css("position")?this.d.container:null],function(b,d){if(d){var c=d[0].style;c.position="absolute";if(2>b)c.removeExpression("height"),c.removeExpression("width"),c.setExpression("height",'document.body.scrollHeight > document.body.clientHeight ? document.body.scrollHeight : document.body.clientHeight + "px"'),c.setExpression("width",'document.body.scrollWidth > document.body.clientWidth ? document.body.scrollWidth : document.body.clientWidth + "px"');else{var f,e;a&&
a.constructor===Array?(f=a[0]?"number"===typeof a[0]?a[0].toString():a[0].replace(/px/,""):d.css("top").replace(/px/,""),f=-1===f.indexOf("%")?f+' + (t = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"':parseInt(f.replace(/%/,""))+' * ((document.documentElement.clientHeight || document.body.clientHeight) / 100) + (t = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"',a[1]&&(e="number"===
typeof a[1]?a[1].toString():a[1].replace(/px/,""),e=-1===e.indexOf("%")?e+' + (t = document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft) + "px"':parseInt(e.replace(/%/,""))+' * ((document.documentElement.clientWidth || document.body.clientWidth) / 100) + (t = document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft) + "px"')):(f='(document.documentElement.clientHeight || document.body.clientHeight) / 2 - (this.offsetHeight / 2) + (t = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"',
e='(document.documentElement.clientWidth || document.body.clientWidth) / 2 - (this.offsetWidth / 2) + (t = document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft) + "px"');c.removeExpression("top");c.removeExpression("left");c.setExpression("top",f);c.setExpression("left",e)}}})},focus:function(a){var d=this;a=a&&-1!==b.inArray(a,["first","last"])?a:"first";var c=b(":input:enabled:visible:"+a,d.d.wrap);setTimeout(function(){0<c.length?c.focus():d.d.wrap.focus()},
10)},getDimensions:function(){var a="undefined"===typeof window.innerHeight?e.height():window.innerHeight;c=[h.height(),h.width()];d=[a,e.width()]},getVal:function(a,b){return a?"number"===typeof a?a:"auto"===a?0:0<a.indexOf("%")?parseInt(a.replace(/%/,""))/100*("h"===b?d[0]:d[1]):parseInt(a.replace(/px/,"")):null},update:function(a,b){if(!this.d.data)return!1;this.d.origHeight=this.getVal(a,"h");this.d.origWidth=this.getVal(b,"w");this.d.data.hide();a&&this.d.container.css("height",a);b&&this.d.container.css("width",
b);this.setContainerDimensions();this.d.data.show();this.o.focus&&this.focus();this.unbindEvents();this.bindEvents()},setContainerDimensions:function(){var a=l||q,b=this.d.origHeight?this.d.origHeight:m?this.d.container.height():this.getVal(a?this.d.container[0].currentStyle.height:this.d.container.css("height"),"h"),a=this.d.origWidth?this.d.origWidth:m?this.d.container.width():this.getVal(a?this.d.container[0].currentStyle.width:this.d.container.css("width"),"w"),c=this.d.data.outerHeight(!0),e=
this.d.data.outerWidth(!0);this.d.origHeight=this.d.origHeight||b;this.d.origWidth=this.d.origWidth||a;var f=this.o.maxHeight?this.getVal(this.o.maxHeight,"h"):null,h=this.o.maxWidth?this.getVal(this.o.maxWidth,"w"):null,f=f&&f<d[0]?f:d[0],h=h&&h<d[1]?h:d[1],g=this.o.minHeight?this.getVal(this.o.minHeight,"h"):"auto",b=b?this.o.autoResize&&b>f?f:b<g?g:b:c?c>f?f:this.o.minHeight&&"auto"!==g&&c<g?g:c:g,f=this.o.minWidth?this.getVal(this.o.minWidth,"w"):"auto",a=a?this.o.autoResize&&a>h?h:a<f?f:a:e?
e>h?h:this.o.minWidth&&"auto"!==f&&e<f?f:e:f;this.d.container.css({height:b,width:a});this.d.wrap.css({overflow:c>b||e>a?"auto":"visible"});this.o.autoPosition&&this.setPosition()},setPosition:function(){var a,b;a=d[0]/2-this.d.container.outerHeight(!0)/2;b=d[1]/2-this.d.container.outerWidth(!0)/2;var c="fixed"!==this.d.container.css("position")?e.scrollTop():0;this.o.position&&"[object Array]"===Object.prototype.toString.call(this.o.position)?(a=c+(this.o.position[0]||a),b=this.o.position[1]||b):
a=c+a;this.d.container.css({left:b,top:a})},watchTab:function(a){if(0<b(a.target).parents(".simplemodal-container").length){if(this.inputs=b(":input:enabled:visible:first, :input:enabled:visible:last",this.d.data[0]),!a.shiftKey&&a.target===this.inputs[this.inputs.length-1]||a.shiftKey&&a.target===this.inputs[0]||0===this.inputs.length)a.preventDefault(),this.focus(a.shiftKey?"last":"first")}else a.preventDefault(),this.focus()},open:function(){this.d.iframe&&this.d.iframe.show();b.isFunction(this.o.onOpen)?
this.o.onOpen.apply(this,[this.d]):(this.d.overlay.show(),this.d.container.show(),this.d.data.show());this.o.focus&&this.focus();this.bindEvents()},close:function(){if(!this.d.data)return!1;this.unbindEvents();if(b.isFunction(this.o.onClose)&&!this.occb)this.occb=!0,this.o.onClose.apply(this,[this.d]);else{if(this.d.placeholder){var a=b("#simplemodal-placeholder");this.o.persist?a.replaceWith(this.d.data.removeClass("simplemodal-data").css("display",this.display)):(this.d.data.hide().remove(),a.replaceWith(this.d.orig))}else this.d.data.hide().remove();
this.d.container.hide().remove();this.d.overlay.hide();this.d.iframe&&this.d.iframe.hide().remove();this.d.overlay.remove();this.d={}}}}});
$(function(){var b=new Kinetic.Stage({container:"birds",width:window.innerWidth,height:window.innerHeight}),c=new Kinetic.Layer({width:b.getWidth(),height:b.getHeight()});b.add(c);birdAnimations.start(b,c);bombui.init("carousel");bombui.setWidth($("#carousel").width());$("#app-store .iphone").click(function(b){$("#iphone-not-ready").modal({overlayClose:!0,autoResize:!0,autoPosition:!0});return!1});$(window).resize(_.debounce(function(c){bombui.setWidth($("#carousel").width());b.setWidth($(document).width());
b.setHeight($(document).height())},100));$(window).on("mousedown touchstart",function(b){birdAnimations.onClick({x:b.clientX,y:b.clientY})})});